gText_ObtainedTheItem::
	.string "Obtenu: {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "Le SAC est plein…$"

gText_PutItemInPocket::
	.string "{PLAYER} met {STR_VAR_2} dans\nPOCHE {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} trouve {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "Dommage!\nLe SAC est plein.$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} met {STR_VAR_2} dans\nle SAC.$"

gText_ObtainedTheDecor::
	.string "Obtenu: {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "Dommage! Il n'y a plus assez de place\npour {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Transfert de {STR_VAR_2} sur le PC.$"

gText_ObtainedTheItems::
	.string "Obtenu: {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} trouve {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} a mis les PIÈCES dans\n"
	.string "le PORTE-MONNAIE.$"

gText_FoundXCoins::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} trouve\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Mince!\n"
	.string "Le PORTE-MONNAIE est plein…$"

gText_NothingToPutThemIn::
	.string "Dommage!\n"
	.string "Il n'y a rien pour les mettre…$"
