gBirchDexRatingText_AreYouCurious::
	.string "PROF. SEKO: Ah, {PLAYER}{KUN}!\pTu veux que je te donne mon avis\nsur ton POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "Hum? Oh, tu n'as pas attrapé assez\nde POKéMON pour que ça en vaille\lla peine.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hum…\pTu as rencontré {STR_VAR_1} POKéMON\net tu en as attrapé {STR_VAR_2}…$"

gBirchDexRatingText_LessThan10::
	.string "Tu devrais aller plus souvent dans\nles herbes et mieux chercher\lles POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Je suppose que tu as bien\ncompris ça. Mais désormais,\lça va devenir plus dur.$"

gBirchDexRatingText_LessThan30::
	.string "Certains POKéMON n'apparaissent\nque dans des zones précises.\lSois tenace!$"

gBirchDexRatingText_LessThan40::
	.string "Bon, il pourrait être un peu plus\nrempli, mais il ressemble déjà plus\là un POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Hé, il commence à être plutôt\npas mal. Continue sur ta lancée!$"

gBirchDexRatingText_LessThan60::
	.string "Est-ce que tu utilises des CANNES?\nIl y a beaucoup de POKéMON\ldans la mer.$"

gBirchDexRatingText_LessThan70::
	.string "Plutôt que juste attraper des\nPOKéMON, pourquoi ne pas aussi\lles faire évoluer?$"

gBirchDexRatingText_LessThan80::
	.string "Ce POKéDEX va être formidable.\nJ'en ai bien l'impression.$"

gBirchDexRatingText_LessThan90::
	.string "Tu as collecté tout ça…\nTu as un talent remarquable!$"

gBirchDexRatingText_LessThan100::
	.string "As-tu visité le PARC SAFARI?\pJ'ai entendu dire que certains\nPOKéMON ne s'attrapent que là-bas.$"

gBirchDexRatingText_LessThan110::
	.string "Tu as atteint la barre des 100.\nC'est un POKéDEX impressionnant!$"

gBirchDexRatingText_LessThan120::
	.string "En utilisant ECLATE-ROC, tu peux\ntrouver des POKéMON.$"

gBirchDexRatingText_LessThan130::
	.string "Tu devrais faire des échanges pour\nte procurer d'autres POKéMON.$"

gBirchDexRatingText_LessThan140::
	.string "Certains POKéMON évoluent quand\nils aiment vraiment leur DRESSEUR.$"

gBirchDexRatingText_LessThan150::
	.string "Je ne savais pas qu'il y avait\nautant d'espèces de POKéMON\là HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "Il arrive que certains POKéMON\nsortent en grand nombre, telle une\lhorde sauvage.\pNe rate pas ce genre d'occasion!$"

gBirchDexRatingText_LessThan170::
	.string "On a une bonne représentation des\nPOKéMON de la région de HOENN\len regardant ton POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "Je pourrais déjà te donner le titre\nde PROFESSEUR POKéMON!$"

gBirchDexRatingText_LessThan190::
	.string "Avec un POKéDEX aussi bien rempli,\ntu passes en professionnel!$"

gBirchDexRatingText_LessThan200::
	.string "Tu es à deux doigts de compléter\nce POKéDEX. Je le vois!$"

gBirchDexRatingText_DexCompleted::
	.string "Félicitations!\nTon POKéDEX est complet!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hum…\nSur l'ensemble du territoire…\pTu as rencontré {STR_VAR_1} POKéMON\net tu as attrapé {STR_VAR_2} POKéMON…$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
