# 1 "data/maps/RouteAlleeGolri/scripts.pory"

# 2 "data/maps/RouteAlleeGolri/scripts.pory"
RouteAlleeGolri_MapScripts::
# 3 "data/maps/RouteAlleeGolri/scripts.pory"
	.byte 0
# 4 "data/maps/RouteAlleeGolri/scripts.pory"

# 5 "data/maps/RouteAlleeGolri/scripts.pory"
RouteAlleeGolri_OnTransition:
# 6 "data/maps/RouteAlleeGolri/scripts.pory"
	setflag FLAG_TEMP_12
# 7 "data/maps/RouteAlleeGolri/scripts.pory"
	end
